# Generated by Django 4.0.1 on 2022-02-04 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myface', '0002_documentlist_photolist_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentList',
        ),
    ]
